### ISSUE TITLE
Inputs do not occupy the same physical space!

### ISSUE THREAD

**Issue by liamheng** [ntustison/antsAtroposN4Example#1]
Hello,

thank you so much for providing this example.
I'm trying to apply it on my data. However I got following error:
Exception caught: 
itk::ExceptionObject (0x2a0ad20)
Location: "unknown" 
File: /root/build/ITKv4-install/include/ITK-4.11/itkImageToImageFilter.hxx
Line: 250
Description: itk::ERROR: N4BiasFieldCorrectionImageFilter(0x29fbaf0): Inputs do not occupy the same physical space! 
InputImage Origin: [0.0000000e+00, 0.0000000e+00], InputImage_1 Origin: [-2.0000000e+00, -2.0000000e+00]
        Tolerance: 2.0000000e-06
InputImage Direction: 1.0000000e+00 0.0000000e+00
0.0000000e+00 1.0000000e+00
, InputImage_1 Direction: -1.0000000e+00 0.0000000e+00
0.0000000e+00 -1.0000000e+00

        Tolerance: 1.0000000e-06

How can I fix this?

Appreciate it a lot.

Heng

**Comment by ntustison** [comment]
Hi Heng,

I just ran it on my computer and didn't have any problems.  Your issue looks like a problem we corrected awhile back.  Can you update your ANTs program directly from the github repo and see if you still get that error?

Nick

**Comment by liamheng** [comment]
Hi Nick.

Thank you for reply. Actually, I can run the example correctly as well. However, when I apply it on my data, this problem occurs.
I use the code as:

#!/bin/bash
DATA_DIR=${PWD}
OUT_DIR=${PWD}

bash ${ANTSPATH}/antsAtroposN4.sh \
  -d 2 \
  -a ${DATA_DIR}/T1_NORMALIZED.nii.gz \
  -x ${DATA_DIR}/MASK_slice17.nii.gz \
  -c 4\
  -o ${OUT_DIR}Atroposexample

And data is as attachment
[MASK_slice17.nii.gz](https://github.com/ntustison/antsAtroposN4Example/files/622662/MASK_slice17.nii.gz)
[T1_NORMALIZED.nii.gz](https://github.com/ntustison/antsAtroposN4Example/files/622661/T1_NORMALIZED.nii.gz)

And I have no ideal what is wrong.

Thank you.

Heng

**Comment by ntustison** [comment]
Your two images have different orientations when read in as 2-d images.

```
$ GetImageInformation 2 T1_NORMALIZED.nii 
Image information
  Size:          [216, 216]
  Origin:        [-1, -1]
  SpatialExtent: [215, 215]
  Center:        [106.5, 106.5]
  Spacing:       [1, 1]
  Index:         [0, 0]
  Direction:     
1 0
0 1

$ GetImageInformation 2 MASK_slice17.nii 
Image information
  Size:          [216, 216]
  Origin:        [-1, -1]
  SpatialExtent: [215, 215]
  Center:        [106.5, 106.5]
  Spacing:       [1, 1]
  Index:         [0, 0]
  Direction:     
-1 0
0 -1
```

**Comment by liamheng** [comment]
Thank you so much Nick.

Btw, is GetImageInformation  a command of ANTs? My terminal reply me 'GetImageInformation: Command not found.'

Heng

**Comment by ntustison** [comment]
No, but you can use ``PrintHeader``.

**Comment by liamheng** [comment]
That makes sense.
Thanks a lot.
